version: "3.4"
services:
  charts:
    image: node:alpine
    container_name: charts
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
    command:
      - sh
      - -c
      - |
        npm install
        npm run dev
